
runtime: nodejs
env: flex



manual_scaling:
  instances: 1

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 10
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

